[2023-05-14T05:45:45.931+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: greenery_addresses_data_pipeline.load_data_from_gcs_to_bigquery manual__2023-05-14T05:44:23.238480+00:00 [queued]>
[2023-05-14T05:45:45.938+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: greenery_addresses_data_pipeline.load_data_from_gcs_to_bigquery manual__2023-05-14T05:44:23.238480+00:00 [queued]>
[2023-05-14T05:45:45.939+0000] {taskinstance.py:1288} INFO - 
--------------------------------------------------------------------------------
[2023-05-14T05:45:45.939+0000] {taskinstance.py:1289} INFO - Starting attempt 1 of 1
[2023-05-14T05:45:45.940+0000] {taskinstance.py:1290} INFO - 
--------------------------------------------------------------------------------
[2023-05-14T05:45:45.949+0000] {taskinstance.py:1309} INFO - Executing <Task(PythonOperator): load_data_from_gcs_to_bigquery> on 2023-05-14 05:44:23.238480+00:00
[2023-05-14T05:45:45.954+0000] {standard_task_runner.py:55} INFO - Started process 9597 to run task
[2023-05-14T05:45:45.957+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'greenery_addresses_data_pipeline', 'load_data_from_gcs_to_bigquery', 'manual__2023-05-14T05:44:23.238480+00:00', '--job-id', '23', '--raw', '--subdir', 'DAGS_FOLDER/greenery_addresses_data_pipeline.py', '--cfg-path', '/tmp/tmpyhgn2zmf']
[2023-05-14T05:45:45.959+0000] {standard_task_runner.py:83} INFO - Job 23: Subtask load_data_from_gcs_to_bigquery
[2023-05-14T05:45:46.019+0000] {task_command.py:389} INFO - Running <TaskInstance: greenery_addresses_data_pipeline.load_data_from_gcs_to_bigquery manual__2023-05-14T05:44:23.238480+00:00 [running]> on host 81a59154956d
[2023-05-14T05:45:46.071+0000] {taskinstance.py:1518} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=greenery_addresses_data_pipeline
AIRFLOW_CTX_TASK_ID=load_data_from_gcs_to_bigquery
AIRFLOW_CTX_EXECUTION_DATE=2023-05-14T05:44:23.238480+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-05-14T05:44:23.238480+00:00
[2023-05-14T05:45:46.075+0000] {logging_mixin.py:137} INFO - ##### Start load data: addresses , date: 2023-05-14 from GCS to Big Query #####
[2023-05-14T05:45:47.099+0000] {taskinstance.py:1776} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/greenery_addresses_data_pipeline.py", line 102, in _load_data_from_gcs_to_bigquery
    job.result()
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/bigquery/job/base.py", line 911, in result
    return super(_AsyncJob, self).result(timeout=timeout, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/google/api_core/future/polling.py", line 137, in result
    raise self._exception
google.api_core.exceptions.Forbidden: 403 Access Denied: File gs://deb-greenery-datapipeline/greenery/addresses/addresses-2023-05-14.csv: Access Denied
[2023-05-14T05:45:47.132+0000] {taskinstance.py:1332} INFO - Marking task as FAILED. dag_id=greenery_addresses_data_pipeline, task_id=load_data_from_gcs_to_bigquery, execution_date=20230514T054423, start_date=20230514T054545, end_date=20230514T054547
[2023-05-14T05:45:47.149+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 23 for task load_data_from_gcs_to_bigquery (403 Access Denied: File gs://deb-greenery-datapipeline/greenery/addresses/addresses-2023-05-14.csv: Access Denied; 9597)
[2023-05-14T05:45:47.174+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-05-14T05:45:47.190+0000] {taskinstance.py:2596} INFO - 0 downstream tasks scheduled from follow-on schedule check
